language: python
python:
  - "3.7"
  - "3.7-dev"
  - "3.8-dev" 
  - "nightly" 

install:
  - pip install -r requirements.txt

script:
  - black --check agipy/
  - mypy --ignore-missing-imports agipy/
  - pylint --errors-only agipy/
  - pytest agipy/